export const testUrl = "http://localhost:3000";
export const defaultColor = `rgb(0, 50, 255)`;
export const changingColor = `rgb(210, 82, 225)`;
export const modifiedColor = `rgb(127, 224, 81)`;
export const testInputValueSelector = '[data-cy="inputValue"]';
export const testInputSelector = '[data-test-cy="input"]';
export const testCircleSelector = '[data-cy="circle"]';
export const testButtonAddSelector = '[data-cy="add"]';
export const testButtonAddHeadSelector = '[data-cy="addHead"]';
export const testButtonAddTailSelector = '[data-cy="addTail"]';
export const testButtonAddByIndexSelector = '[data-cy="addByIndex"]';
export const testButtonDelByIndexSelector = '[data-cy="delByIndex"]';
export const testTextHeadSelector = '[data-cy="head"]';
export const testButtonDelSelector = '[data-cy="del"]';
export const testButtonDelHeadSelector = '[data-cy="delHead"]';
export const testButtonDelTailSelector = '[data-cy="delTail"]';
export const testButtonResetSelector = '[data-cy="reset"]';
export const testTextTailSelector = '[data-cy="tail"]';
export const testTopCircleSelector = '[data-cy="topCircle"]';
export const testbottomCircleSelector = '[data-cy="bottomCircel"]';
export const testSmallCircleClass = "[class*=small]";
export const testCircleContSelector = '[data-cy="circle-cont"]';
export const testArrowSelector = '[data-cy="arrow"]';
export const testIndexSelector = '[data-cy="index"]';
export const testInputIndexSelector = '[data-test-cy="inputIndex"]';
